apiVersion: v1
kind: ReplicationController
metadata:
   name: myrc1
spec:
    replicas: 5
    selector:
     app: web
    template:
       metadata:
        name: "mypod2"
        labels:
           app: web
       spec:
        containers:
         - name: "myc1"
<<<<<<< HEAD
           image: "vimal13/apache-webserver-php"
           manj
=======
           image: "vimal13/apache-webserver-php".
>>>>>>> parent of 0b2e4a9 (third change)
